### ISSUE TITLE
Track ansible code changes

### ISSUE THREAD

**Issue by P0intMaN** [P0intMaN/PyAutoCode#8]
Currently, for remote installations pyautocode doesn't have ansible supported. This is an attempt to track all the PRs related to Ansible

**Comment by P0intMaN** [comment]
**Corresponding PRs:**
- #7

**Comment by CYBERDEVILZ** [comment]
Hey @P0intMaN kindly assign this work to me. Let me handle this for ya!

**Comment by P0intMaN** [comment]
@CYBERDEVILZ this is simply an issue to track all the ansible related PRs. I am raising the concerned issues right away. Feel free to contribute in any if you'd like

**Comment by CYBERDEVILZ** [comment]
Okay, thanks for the heads up!

**Comment by P0intMaN** [comment]
All required changes done. Will reopen if need be.
